name: Delve CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - go: 1.15
            os: macos-latest
          - go: 1.14
            os: ubuntu-latest
          - go: 1.13
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{matrix.go}}
      - run: go run _scripts/make.go test
